########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(argon2_COMPONENT_NAMES "")
if(DEFINED argon2_FIND_DEPENDENCY_NAMES)
  list(APPEND argon2_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES argon2_FIND_DEPENDENCY_NAMES)
else()
  set(argon2_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(argon2_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/argonad6abc2338828/p")
set(argon2_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(argon2_INCLUDE_DIRS_RELWITHDEBINFO )
set(argon2_RES_DIRS_RELWITHDEBINFO )
set(argon2_DEFINITIONS_RELWITHDEBINFO )
set(argon2_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(argon2_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(argon2_OBJECTS_RELWITHDEBINFO )
set(argon2_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(argon2_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(argon2_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(argon2_LIB_DIRS_RELWITHDEBINFO "${argon2_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(argon2_BIN_DIRS_RELWITHDEBINFO )
set(argon2_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(argon2_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(argon2_LIBS_RELWITHDEBINFO argon2)
set(argon2_SYSTEM_LIBS_RELWITHDEBINFO )
set(argon2_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(argon2_FRAMEWORKS_RELWITHDEBINFO )
set(argon2_BUILD_DIRS_RELWITHDEBINFO )
set(argon2_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(argon2_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${argon2_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${argon2_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(argon2_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${argon2_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${argon2_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${argon2_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(argon2_COMPONENTS_RELWITHDEBINFO )