########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(lcms_COMPONENT_NAMES "")
if(DEFINED lcms_FIND_DEPENDENCY_NAMES)
  list(APPEND lcms_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES lcms_FIND_DEPENDENCY_NAMES)
else()
  set(lcms_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(lcms_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/lcmsffe25f3f5cf59/p")
set(lcms_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(lcms_INCLUDE_DIRS_RELWITHDEBINFO )
set(lcms_RES_DIRS_RELWITHDEBINFO )
set(lcms_DEFINITIONS_RELWITHDEBINFO )
set(lcms_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(lcms_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(lcms_OBJECTS_RELWITHDEBINFO )
set(lcms_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(lcms_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(lcms_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(lcms_LIB_DIRS_RELWITHDEBINFO "${lcms_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(lcms_BIN_DIRS_RELWITHDEBINFO )
set(lcms_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(lcms_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(lcms_LIBS_RELWITHDEBINFO lcms2)
set(lcms_SYSTEM_LIBS_RELWITHDEBINFO )
set(lcms_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(lcms_FRAMEWORKS_RELWITHDEBINFO )
set(lcms_BUILD_DIRS_RELWITHDEBINFO )
set(lcms_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(lcms_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${lcms_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${lcms_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(lcms_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${lcms_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${lcms_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${lcms_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(lcms_COMPONENTS_RELWITHDEBINFO )