########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(libelf_COMPONENT_NAMES "")
if(DEFINED libelf_FIND_DEPENDENCY_NAMES)
  list(APPEND libelf_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES libelf_FIND_DEPENDENCY_NAMES)
else()
  set(libelf_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(libelf_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/libel3ef084d02c0dc/p")
set(libelf_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(libelf_INCLUDE_DIRS_RELWITHDEBINFO )
set(libelf_RES_DIRS_RELWITHDEBINFO )
set(libelf_DEFINITIONS_RELWITHDEBINFO )
set(libelf_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(libelf_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(libelf_OBJECTS_RELWITHDEBINFO )
set(libelf_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(libelf_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(libelf_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(libelf_LIB_DIRS_RELWITHDEBINFO "${libelf_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(libelf_BIN_DIRS_RELWITHDEBINFO )
set(libelf_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(libelf_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(libelf_LIBS_RELWITHDEBINFO elf)
set(libelf_SYSTEM_LIBS_RELWITHDEBINFO )
set(libelf_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(libelf_FRAMEWORKS_RELWITHDEBINFO )
set(libelf_BUILD_DIRS_RELWITHDEBINFO )
set(libelf_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(libelf_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${libelf_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${libelf_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(libelf_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${libelf_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${libelf_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${libelf_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(libelf_COMPONENTS_RELWITHDEBINFO )