########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(libffi_COMPONENT_NAMES "")
if(DEFINED libffi_FIND_DEPENDENCY_NAMES)
  list(APPEND libffi_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES libffi_FIND_DEPENDENCY_NAMES)
else()
  set(libffi_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(libffi_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/libff92ebfff1bf74e/p")
set(libffi_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(libffi_INCLUDE_DIRS_RELWITHDEBINFO )
set(libffi_RES_DIRS_RELWITHDEBINFO )
set(libffi_DEFINITIONS_RELWITHDEBINFO "-DFFI_STATIC_BUILD")
set(libffi_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(libffi_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(libffi_OBJECTS_RELWITHDEBINFO )
set(libffi_COMPILE_DEFINITIONS_RELWITHDEBINFO "FFI_STATIC_BUILD")
set(libffi_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(libffi_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(libffi_LIB_DIRS_RELWITHDEBINFO "${libffi_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(libffi_BIN_DIRS_RELWITHDEBINFO )
set(libffi_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(libffi_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(libffi_LIBS_RELWITHDEBINFO ffi)
set(libffi_SYSTEM_LIBS_RELWITHDEBINFO )
set(libffi_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(libffi_FRAMEWORKS_RELWITHDEBINFO )
set(libffi_BUILD_DIRS_RELWITHDEBINFO )
set(libffi_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(libffi_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${libffi_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${libffi_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(libffi_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${libffi_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${libffi_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${libffi_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(libffi_COMPONENTS_RELWITHDEBINFO )