########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(libgsf_COMPONENT_NAMES "")
if(DEFINED libgsf_FIND_DEPENDENCY_NAMES)
  list(APPEND libgsf_FIND_DEPENDENCY_NAMES glib libxml2 ZLIB)
  list(REMOVE_DUPLICATES libgsf_FIND_DEPENDENCY_NAMES)
else()
  set(libgsf_FIND_DEPENDENCY_NAMES glib libxml2 ZLIB)
endif()
set(glib_FIND_MODE "NO_MODULE")
set(libxml2_FIND_MODE "NO_MODULE")
set(ZLIB_FIND_MODE "NO_MODULE")

########### VARIABLES #######################################################################
#############################################################################################
set(libgsf_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/libgsfe73a1a172264/p")
set(libgsf_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(libgsf_INCLUDE_DIRS_RELWITHDEBINFO )
set(libgsf_RES_DIRS_RELWITHDEBINFO )
set(libgsf_DEFINITIONS_RELWITHDEBINFO )
set(libgsf_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(libgsf_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(libgsf_OBJECTS_RELWITHDEBINFO )
set(libgsf_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(libgsf_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(libgsf_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(libgsf_LIB_DIRS_RELWITHDEBINFO "${libgsf_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(libgsf_BIN_DIRS_RELWITHDEBINFO )
set(libgsf_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(libgsf_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(libgsf_LIBS_RELWITHDEBINFO gsf-1)
set(libgsf_SYSTEM_LIBS_RELWITHDEBINFO )
set(libgsf_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(libgsf_FRAMEWORKS_RELWITHDEBINFO )
set(libgsf_BUILD_DIRS_RELWITHDEBINFO )
set(libgsf_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(libgsf_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${libgsf_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${libgsf_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(libgsf_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${libgsf_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${libgsf_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${libgsf_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(libgsf_COMPONENTS_RELWITHDEBINFO )