########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(lzo_COMPONENT_NAMES "")
if(DEFINED lzo_FIND_DEPENDENCY_NAMES)
  list(APPEND lzo_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES lzo_FIND_DEPENDENCY_NAMES)
else()
  set(lzo_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(lzo_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/lzo2ae9223db79ac/p")
set(lzo_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(lzo_INCLUDE_DIRS_RELWITHDEBINFO )
set(lzo_RES_DIRS_RELWITHDEBINFO )
set(lzo_DEFINITIONS_RELWITHDEBINFO )
set(lzo_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(lzo_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(lzo_OBJECTS_RELWITHDEBINFO )
set(lzo_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(lzo_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(lzo_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(lzo_LIB_DIRS_RELWITHDEBINFO "${lzo_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(lzo_BIN_DIRS_RELWITHDEBINFO )
set(lzo_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(lzo_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(lzo_LIBS_RELWITHDEBINFO lzo2)
set(lzo_SYSTEM_LIBS_RELWITHDEBINFO )
set(lzo_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(lzo_FRAMEWORKS_RELWITHDEBINFO )
set(lzo_BUILD_DIRS_RELWITHDEBINFO )
set(lzo_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(lzo_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${lzo_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${lzo_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(lzo_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${lzo_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${lzo_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${lzo_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(lzo_COMPONENTS_RELWITHDEBINFO )