########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(expat_COMPONENT_NAMES "")
if(DEFINED expat_FIND_DEPENDENCY_NAMES)
  list(APPEND expat_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES expat_FIND_DEPENDENCY_NAMES)
else()
  set(expat_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(expat_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/expat5d5b36794b388/p")
set(expat_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(expat_INCLUDE_DIRS_RELWITHDEBINFO )
set(expat_RES_DIRS_RELWITHDEBINFO )
set(expat_DEFINITIONS_RELWITHDEBINFO "-DXML_STATIC")
set(expat_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(expat_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(expat_OBJECTS_RELWITHDEBINFO )
set(expat_COMPILE_DEFINITIONS_RELWITHDEBINFO "XML_STATIC")
set(expat_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(expat_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(expat_LIB_DIRS_RELWITHDEBINFO "${expat_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(expat_BIN_DIRS_RELWITHDEBINFO )
set(expat_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(expat_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(expat_LIBS_RELWITHDEBINFO expat)
set(expat_SYSTEM_LIBS_RELWITHDEBINFO )
set(expat_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(expat_FRAMEWORKS_RELWITHDEBINFO )
set(expat_BUILD_DIRS_RELWITHDEBINFO )
set(expat_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(expat_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${expat_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${expat_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(expat_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${expat_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${expat_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${expat_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(expat_COMPONENTS_RELWITHDEBINFO )