########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(libjpeg_COMPONENT_NAMES "")
if(DEFINED libjpeg_FIND_DEPENDENCY_NAMES)
  list(APPEND libjpeg_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES libjpeg_FIND_DEPENDENCY_NAMES)
else()
  set(libjpeg_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(libjpeg_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/libjp24a4974036424/p")
set(libjpeg_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(libjpeg_INCLUDE_DIRS_RELWITHDEBINFO )
set(libjpeg_RES_DIRS_RELWITHDEBINFO "${libjpeg_PACKAGE_FOLDER_RELWITHDEBINFO}/res")
set(libjpeg_DEFINITIONS_RELWITHDEBINFO "-DLIBJPEG_STATIC")
set(libjpeg_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(libjpeg_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(libjpeg_OBJECTS_RELWITHDEBINFO )
set(libjpeg_COMPILE_DEFINITIONS_RELWITHDEBINFO "LIBJPEG_STATIC")
set(libjpeg_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(libjpeg_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(libjpeg_LIB_DIRS_RELWITHDEBINFO "${libjpeg_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(libjpeg_BIN_DIRS_RELWITHDEBINFO )
set(libjpeg_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(libjpeg_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(libjpeg_LIBS_RELWITHDEBINFO jpeg)
set(libjpeg_SYSTEM_LIBS_RELWITHDEBINFO )
set(libjpeg_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(libjpeg_FRAMEWORKS_RELWITHDEBINFO )
set(libjpeg_BUILD_DIRS_RELWITHDEBINFO )
set(libjpeg_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(libjpeg_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${libjpeg_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${libjpeg_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(libjpeg_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${libjpeg_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${libjpeg_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${libjpeg_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(libjpeg_COMPONENTS_RELWITHDEBINFO )