########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(libpng_COMPONENT_NAMES "")
if(DEFINED libpng_FIND_DEPENDENCY_NAMES)
  list(APPEND libpng_FIND_DEPENDENCY_NAMES ZLIB)
  list(REMOVE_DUPLICATES libpng_FIND_DEPENDENCY_NAMES)
else()
  set(libpng_FIND_DEPENDENCY_NAMES ZLIB)
endif()
set(ZLIB_FIND_MODE "MODULE")

########### VARIABLES #######################################################################
#############################################################################################
set(libpng_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/libpnf27a3aae24024/p")
set(libpng_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(libpng_INCLUDE_DIRS_RELWITHDEBINFO )
set(libpng_RES_DIRS_RELWITHDEBINFO )
set(libpng_DEFINITIONS_RELWITHDEBINFO )
set(libpng_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(libpng_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(libpng_OBJECTS_RELWITHDEBINFO )
set(libpng_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(libpng_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(libpng_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(libpng_LIB_DIRS_RELWITHDEBINFO "${libpng_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(libpng_BIN_DIRS_RELWITHDEBINFO )
set(libpng_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(libpng_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(libpng_LIBS_RELWITHDEBINFO png)
set(libpng_SYSTEM_LIBS_RELWITHDEBINFO m)
set(libpng_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(libpng_FRAMEWORKS_RELWITHDEBINFO )
set(libpng_BUILD_DIRS_RELWITHDEBINFO )
set(libpng_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(libpng_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${libpng_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${libpng_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(libpng_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${libpng_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${libpng_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${libpng_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(libpng_COMPONENTS_RELWITHDEBINFO )