########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(giflib_COMPONENT_NAMES "")
if(DEFINED giflib_FIND_DEPENDENCY_NAMES)
  list(APPEND giflib_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES giflib_FIND_DEPENDENCY_NAMES)
else()
  set(giflib_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(giflib_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/giflieaccfd1e3326f/p")
set(giflib_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(giflib_INCLUDE_DIRS_RELWITHDEBINFO )
set(giflib_RES_DIRS_RELWITHDEBINFO )
set(giflib_DEFINITIONS_RELWITHDEBINFO )
set(giflib_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(giflib_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(giflib_OBJECTS_RELWITHDEBINFO )
set(giflib_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(giflib_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(giflib_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(giflib_LIB_DIRS_RELWITHDEBINFO "${giflib_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(giflib_BIN_DIRS_RELWITHDEBINFO )
set(giflib_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(giflib_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(giflib_LIBS_RELWITHDEBINFO gif)
set(giflib_SYSTEM_LIBS_RELWITHDEBINFO )
set(giflib_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(giflib_FRAMEWORKS_RELWITHDEBINFO )
set(giflib_BUILD_DIRS_RELWITHDEBINFO )
set(giflib_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(giflib_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${giflib_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${giflib_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(giflib_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${giflib_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${giflib_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${giflib_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(giflib_COMPONENTS_RELWITHDEBINFO )