########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

list(APPEND pcre2_COMPONENT_NAMES PCRE2::8BIT PCRE2::16BIT PCRE2::32BIT PCRE2::POSIX)
list(REMOVE_DUPLICATES pcre2_COMPONENT_NAMES)
if(DEFINED pcre2_FIND_DEPENDENCY_NAMES)
  list(APPEND pcre2_FIND_DEPENDENCY_NAMES BZip2 ZLIB)
  list(REMOVE_DUPLICATES pcre2_FIND_DEPENDENCY_NAMES)
else()
  set(pcre2_FIND_DEPENDENCY_NAMES BZip2 ZLIB)
endif()
set(BZip2_FIND_MODE "NO_MODULE")
set(ZLIB_FIND_MODE "NO_MODULE")

########### VARIABLES #######################################################################
#############################################################################################
set(pcre2_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/pcre212ff88f62bfae/p")
set(pcre2_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(pcre2_INCLUDE_DIRS_RELWITHDEBINFO )
set(pcre2_RES_DIRS_RELWITHDEBINFO )
set(pcre2_DEFINITIONS_RELWITHDEBINFO "-DPCRE2_STATIC")
set(pcre2_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(pcre2_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(pcre2_OBJECTS_RELWITHDEBINFO )
set(pcre2_COMPILE_DEFINITIONS_RELWITHDEBINFO "PCRE2_STATIC")
set(pcre2_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(pcre2_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(pcre2_LIB_DIRS_RELWITHDEBINFO "${pcre2_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(pcre2_BIN_DIRS_RELWITHDEBINFO )
set(pcre2_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(pcre2_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(pcre2_LIBS_RELWITHDEBINFO pcre2-posix pcre2-32 pcre2-16 pcre2-8)
set(pcre2_SYSTEM_LIBS_RELWITHDEBINFO )
set(pcre2_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(pcre2_FRAMEWORKS_RELWITHDEBINFO )
set(pcre2_BUILD_DIRS_RELWITHDEBINFO )
set(pcre2_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(pcre2_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${pcre2_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${pcre2_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(pcre2_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pcre2_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pcre2_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pcre2_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(pcre2_COMPONENTS_RELWITHDEBINFO PCRE2::8BIT PCRE2::16BIT PCRE2::32BIT PCRE2::POSIX)
########### COMPONENT PCRE2::POSIX VARIABLES ############################################

set(pcre2_PCRE2_POSIX_INCLUDE_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_LIB_DIRS_RELWITHDEBINFO "${pcre2_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(pcre2_PCRE2_POSIX_BIN_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(pcre2_PCRE2_POSIX_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(pcre2_PCRE2_POSIX_RES_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_DEFINITIONS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_OBJECTS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(pcre2_PCRE2_POSIX_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(pcre2_PCRE2_POSIX_LIBS_RELWITHDEBINFO pcre2-posix)
set(pcre2_PCRE2_POSIX_SYSTEM_LIBS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_FRAMEWORKS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_DEPENDENCIES_RELWITHDEBINFO PCRE2::8BIT)
set(pcre2_PCRE2_POSIX_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(pcre2_PCRE2_POSIX_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(pcre2_PCRE2_POSIX_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pcre2_PCRE2_POSIX_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pcre2_PCRE2_POSIX_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pcre2_PCRE2_POSIX_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(pcre2_PCRE2_POSIX_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${pcre2_PCRE2_POSIX_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${pcre2_PCRE2_POSIX_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
########### COMPONENT PCRE2::32BIT VARIABLES ############################################

set(pcre2_PCRE2_32BIT_INCLUDE_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_32BIT_LIB_DIRS_RELWITHDEBINFO "${pcre2_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(pcre2_PCRE2_32BIT_BIN_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_32BIT_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(pcre2_PCRE2_32BIT_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(pcre2_PCRE2_32BIT_RES_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_32BIT_DEFINITIONS_RELWITHDEBINFO "-DPCRE2_STATIC")
set(pcre2_PCRE2_32BIT_OBJECTS_RELWITHDEBINFO )
set(pcre2_PCRE2_32BIT_COMPILE_DEFINITIONS_RELWITHDEBINFO "PCRE2_STATIC")
set(pcre2_PCRE2_32BIT_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(pcre2_PCRE2_32BIT_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(pcre2_PCRE2_32BIT_LIBS_RELWITHDEBINFO pcre2-32)
set(pcre2_PCRE2_32BIT_SYSTEM_LIBS_RELWITHDEBINFO )
set(pcre2_PCRE2_32BIT_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_32BIT_FRAMEWORKS_RELWITHDEBINFO )
set(pcre2_PCRE2_32BIT_DEPENDENCIES_RELWITHDEBINFO )
set(pcre2_PCRE2_32BIT_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(pcre2_PCRE2_32BIT_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(pcre2_PCRE2_32BIT_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(pcre2_PCRE2_32BIT_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pcre2_PCRE2_32BIT_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pcre2_PCRE2_32BIT_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pcre2_PCRE2_32BIT_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(pcre2_PCRE2_32BIT_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${pcre2_PCRE2_32BIT_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${pcre2_PCRE2_32BIT_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
########### COMPONENT PCRE2::16BIT VARIABLES ############################################

set(pcre2_PCRE2_16BIT_INCLUDE_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_16BIT_LIB_DIRS_RELWITHDEBINFO "${pcre2_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(pcre2_PCRE2_16BIT_BIN_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_16BIT_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(pcre2_PCRE2_16BIT_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(pcre2_PCRE2_16BIT_RES_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_16BIT_DEFINITIONS_RELWITHDEBINFO "-DPCRE2_STATIC")
set(pcre2_PCRE2_16BIT_OBJECTS_RELWITHDEBINFO )
set(pcre2_PCRE2_16BIT_COMPILE_DEFINITIONS_RELWITHDEBINFO "PCRE2_STATIC")
set(pcre2_PCRE2_16BIT_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(pcre2_PCRE2_16BIT_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(pcre2_PCRE2_16BIT_LIBS_RELWITHDEBINFO pcre2-16)
set(pcre2_PCRE2_16BIT_SYSTEM_LIBS_RELWITHDEBINFO )
set(pcre2_PCRE2_16BIT_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_16BIT_FRAMEWORKS_RELWITHDEBINFO )
set(pcre2_PCRE2_16BIT_DEPENDENCIES_RELWITHDEBINFO )
set(pcre2_PCRE2_16BIT_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(pcre2_PCRE2_16BIT_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(pcre2_PCRE2_16BIT_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(pcre2_PCRE2_16BIT_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pcre2_PCRE2_16BIT_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pcre2_PCRE2_16BIT_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pcre2_PCRE2_16BIT_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(pcre2_PCRE2_16BIT_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${pcre2_PCRE2_16BIT_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${pcre2_PCRE2_16BIT_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
########### COMPONENT PCRE2::8BIT VARIABLES ############################################

set(pcre2_PCRE2_8BIT_INCLUDE_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_8BIT_LIB_DIRS_RELWITHDEBINFO "${pcre2_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(pcre2_PCRE2_8BIT_BIN_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_8BIT_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(pcre2_PCRE2_8BIT_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(pcre2_PCRE2_8BIT_RES_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_8BIT_DEFINITIONS_RELWITHDEBINFO "-DPCRE2_STATIC")
set(pcre2_PCRE2_8BIT_OBJECTS_RELWITHDEBINFO )
set(pcre2_PCRE2_8BIT_COMPILE_DEFINITIONS_RELWITHDEBINFO "PCRE2_STATIC")
set(pcre2_PCRE2_8BIT_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(pcre2_PCRE2_8BIT_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(pcre2_PCRE2_8BIT_LIBS_RELWITHDEBINFO pcre2-8)
set(pcre2_PCRE2_8BIT_SYSTEM_LIBS_RELWITHDEBINFO )
set(pcre2_PCRE2_8BIT_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(pcre2_PCRE2_8BIT_FRAMEWORKS_RELWITHDEBINFO )
set(pcre2_PCRE2_8BIT_DEPENDENCIES_RELWITHDEBINFO ZLIB::ZLIB BZip2::BZip2)
set(pcre2_PCRE2_8BIT_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(pcre2_PCRE2_8BIT_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(pcre2_PCRE2_8BIT_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(pcre2_PCRE2_8BIT_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pcre2_PCRE2_8BIT_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pcre2_PCRE2_8BIT_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pcre2_PCRE2_8BIT_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(pcre2_PCRE2_8BIT_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${pcre2_PCRE2_8BIT_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${pcre2_PCRE2_8BIT_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")