########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(pixman_COMPONENT_NAMES "")
if(DEFINED pixman_FIND_DEPENDENCY_NAMES)
  list(APPEND pixman_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES pixman_FIND_DEPENDENCY_NAMES)
else()
  set(pixman_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(pixman_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/pixmac7396c96fcd17/p")
set(pixman_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(pixman_INCLUDE_DIRS_RELWITHDEBINFO )
set(pixman_RES_DIRS_RELWITHDEBINFO )
set(pixman_DEFINITIONS_RELWITHDEBINFO )
set(pixman_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(pixman_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(pixman_OBJECTS_RELWITHDEBINFO )
set(pixman_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(pixman_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(pixman_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(pixman_LIB_DIRS_RELWITHDEBINFO "${pixman_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(pixman_BIN_DIRS_RELWITHDEBINFO )
set(pixman_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(pixman_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(pixman_LIBS_RELWITHDEBINFO pixman-1)
set(pixman_SYSTEM_LIBS_RELWITHDEBINFO )
set(pixman_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(pixman_FRAMEWORKS_RELWITHDEBINFO )
set(pixman_BUILD_DIRS_RELWITHDEBINFO )
set(pixman_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(pixman_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${pixman_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${pixman_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(pixman_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pixman_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pixman_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pixman_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(pixman_COMPONENTS_RELWITHDEBINFO )