########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(wvware_COMPONENT_NAMES "")
if(DEFINED wvware_FIND_DEPENDENCY_NAMES)
  list(APPEND wvware_FIND_DEPENDENCY_NAMES libgsf glib PNG libxml2 ZLIB Iconv)
  list(REMOVE_DUPLICATES wvware_FIND_DEPENDENCY_NAMES)
else()
  set(wvware_FIND_DEPENDENCY_NAMES libgsf glib PNG libxml2 ZLIB Iconv)
endif()
set(libgsf_FIND_MODE "NO_MODULE")
set(glib_FIND_MODE "NO_MODULE")
set(PNG_FIND_MODE "NO_MODULE")
set(libxml2_FIND_MODE "NO_MODULE")
set(ZLIB_FIND_MODE "NO_MODULE")
set(Iconv_FIND_MODE "NO_MODULE")

########### VARIABLES #######################################################################
#############################################################################################
set(wvware_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/PC/.conan2/p/wvwarb2f91e9c30400/p")
set(wvware_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(wvware_INCLUDE_DIRS_RELWITHDEBINFO )
set(wvware_RES_DIRS_RELWITHDEBINFO "${wvware_PACKAGE_FOLDER_RELWITHDEBINFO}/share/wv")
set(wvware_DEFINITIONS_RELWITHDEBINFO )
set(wvware_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(wvware_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(wvware_OBJECTS_RELWITHDEBINFO )
set(wvware_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(wvware_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(wvware_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(wvware_LIB_DIRS_RELWITHDEBINFO "${wvware_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(wvware_BIN_DIRS_RELWITHDEBINFO )
set(wvware_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(wvware_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(wvware_LIBS_RELWITHDEBINFO wv)
set(wvware_SYSTEM_LIBS_RELWITHDEBINFO m)
set(wvware_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(wvware_FRAMEWORKS_RELWITHDEBINFO )
set(wvware_BUILD_DIRS_RELWITHDEBINFO )
set(wvware_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(wvware_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${wvware_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${wvware_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(wvware_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${wvware_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${wvware_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${wvware_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(wvware_COMPONENTS_RELWITHDEBINFO )